### ISSUE TITLE
✨ User password change

### ISSUE THREAD

**Issue by thatonejason** [CodingZeal/redwood-template-app#89]
## Story

**In order to change my own password**
**As a user**
**I need a way to change my password**

## Acceptance Criteria

- User profile should include a password change ability
- New password should adhere to password validation rules
- All Existing sessions should expire across all connections
- User should be logged out
- Should apply to all users regardless of role

**Comment by house9** [comment]
PR ready for review: https://github.com/CodingZeal/redwood-template-app/pull/96

> User profile should include a password change ability

👍 

> New password should adhere to password validation rules

We don't currently have any 😮 thinking that should be created as a separate ticket, since it will effect multiple areas of the application

> All Existing sessions should expire across all connections

I believe redwoodjs uses a cookie for the session and there is no way to remove cookies set on other devices/browsers, would require saving sessions in the database instead, if we want to go that route we should probably do that on a new ticket as well

> User should be logged out

This has not been implemented yet, but wondering if we really want to do this? Shouldn't be difficult to do but might not be the best user experience?

> Should apply to all users regardless of role

👍

**Comment by thatonejason** [comment]
Thanks for the feedback, @house9. 

I should've been more clear about the intent to preserve and/or follow existing rules and practices (such as validation) rather than create new ones. IMO validation rules, what happens when a password changes, etc., are open for discussion so I'm 👍 with the basic functionality and leave it up to the team to decide on the rest.
